import { TrigramType } from '@/_models/Trigram';

type HexagramChart = Record<TrigramType, Record<TrigramType, number>>;

export const HEXAGRAM_CHART: HexagramChart = {
  [TrigramType.Heaven]: {
    [TrigramType.Heaven]: 1,
    [TrigramType.Lake]: 43,
    [TrigramType.Fire]: 14,
    [TrigramType.Thunder]: 34,
    [TrigramType.Wind]: 9,
    [TrigramType.Water]: 5,
    [TrigramType.Mountain]: 26,
    [TrigramType.Earth]: 11,
  },
  [TrigramType.Lake]: {
    [TrigramType.Heaven]: 10,
    [TrigramType.Lake]: 58,
    [TrigramType.Fire]: 38,
    [TrigramType.Thunder]: 54,
    [TrigramType.Wind]: 61,
    [TrigramType.Water]: 60,
    [TrigramType.Mountain]: 41,
    [TrigramType.Earth]: 19,
  },
  [TrigramType.Fire]: {
    [TrigramType.Heaven]: 13,
    [TrigramType.Lake]: 49,
    [TrigramType.Fire]: 30,
    [TrigramType.Thunder]: 55,
    [TrigramType.Wind]: 37,
    [TrigramType.Water]: 63,
    [TrigramType.Mountain]: 22,
    [TrigramType.Earth]: 36,
  },
  [TrigramType.Thunder]: {
    [TrigramType.Heaven]: 25,
    [TrigramType.Lake]: 17,
    [TrigramType.Fire]: 21,
    [TrigramType.Thunder]: 51,
    [TrigramType.Wind]: 42,
    [TrigramType.Water]: 3,
    [TrigramType.Mountain]: 27,
    [TrigramType.Earth]: 24,
  },
  [TrigramType.Wind]: {
    [TrigramType.Heaven]: 44,
    [TrigramType.Lake]: 28,
    [TrigramType.Fire]: 50,
    [TrigramType.Thunder]: 32,
    [TrigramType.Wind]: 57,
    [TrigramType.Water]: 48,
    [TrigramType.Mountain]: 18,
    [TrigramType.Earth]: 46,
  },
  [TrigramType.Water]: {
    [TrigramType.Heaven]: 6,
    [TrigramType.Lake]: 47,
    [TrigramType.Fire]: 64,
    [TrigramType.Thunder]: 40,
    [TrigramType.Wind]: 59,
    [TrigramType.Water]: 29,
    [TrigramType.Mountain]: 4,
    [TrigramType.Earth]: 7,
  },
  [TrigramType.Mountain]: {
    [TrigramType.Heaven]: 33,
    [TrigramType.Lake]: 31,
    [TrigramType.Fire]: 56,
    [TrigramType.Thunder]: 62,
    [TrigramType.Wind]: 53,
    [TrigramType.Water]: 39,
    [TrigramType.Mountain]: 52,
    [TrigramType.Earth]: 15,
  },
  [TrigramType.Earth]: {
    [TrigramType.Heaven]: 12,
    [TrigramType.Lake]: 45,
    [TrigramType.Fire]: 35,
    [TrigramType.Thunder]: 16,
    [TrigramType.Wind]: 20,
    [TrigramType.Water]: 8,
    [TrigramType.Mountain]: 23,
    [TrigramType.Earth]: 2,
  },
};
